spring.application.name=shopping_list

spring.profiles.active=local

# ????????? ?????????? docker-compose (????? ????? ?? ?????? Docker)
spring.docker.compose.enabled=false

# ????????? Liquibase
spring.liquibase.enabled=false

# ????????? H2 in-memory
spring.datasource.url=jdbc:h2:mem:shopping_list;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# ????????????? ????? (???? ???? ??? Liquibase)
spring.jpa.hibernate.ddl-auto=update

# H2-??????? (?????? ?????????? ???????)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

rates.api.base=USD
rates.api.url=https://api.frankfurter.dev/v1
